import { Inter } from "next/font/google";
import { Metadata } from 'next';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Gen Invetory App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        href: '/favicon.ico'
      },
    ],
  },
};


export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <head>
          <title>{metadata.title}</title>
          <meta name="description" content={metadata.description} />
        </head>
        <body className={inter.className}>{children}</body>
      </html>

  );
}
